### ISSUE TITLE
Ошибка загрузки config.py

### ISSUE THREAD

**Issue by nikitas244** [onstabb/StayHome-Telegram-Bot#1]
```
root@vm1533475:~/Stay# python3.8 Bot.py
Traceback (most recent call last):
  File "Bot.py", line 2, in <module>
    import config
  File "/root/Stay/config.py", line 4, in <module>
    ADMIN = int(os.environ.get('ADMIN'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

Уже менял в "скобках" на свой цифровой ID, но все равно не хочет бот включаться. :( 
Все библиотеки нужные подключил.

**Comment by onstabb** [comment]
Нужно еще запустить единожды dbworker.py для создания sqlite файла с таблицей. Тогда должно всё работать.

**Comment by onstabb** [comment]
> ```
> root@vm1533475:~/Stay# python3.8 Bot.py
> Traceback (most recent call last):
>   File "Bot.py", line 2, in <module>
>     import config
>   File "/root/Stay/config.py", line 4, in <module>
>     ADMIN = int(os.environ.get('ADMIN'))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> ```
> 
> Уже менял в "скобках" на свой цифровой ID, но все равно не хочет бот включаться. :(
> Все библиотеки нужные подключил.

Необходимо еще единожды запустить dbworker.py для создания sqlite файла с таблицей. Тогда всё должно работать.

**Comment by nikitas244** [comment]
Делал всё так, как и указали, но ошибка выходит та же самая. :(

**Comment by nikitas244** [comment]
root@vm1533475:~/Stay# python3.8 dbworker.py
Traceback (most recent call last):
  File "dbworker.py", line 2, in <module>
    import config
  File "/root/Stay/config.py", line 4, in <module>
    ADMIN = int(os.environ.get('79889'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by onstabb** [comment]
> root@vm1533475:~/Stay# python3.8 dbworker.py
> Traceback (most recent call last):
> File "dbworker.py", line 2, in
> import config
> File "/root/Stay/config.py", line 4, in
> ADMIN = int(os.environ.get('79889'))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Вы должны подставить ADMIN = 79889
os.environ.get() - метод, который возвращает значение в словаре переменных окружения.

**Comment by nikitas244** [comment]
Как-то даже неловко вышло... 

Всё запустилось отлично, но при "выходе на улицу" ругается что нет файла "FileNotFoundError: [Errno 2] No such file or directory: 'situation.world'"

**Comment by nikitas244** [comment]
Пробовал даже сам создать файл, но, увы. Из-за этого не работает «прогулка». 👉🏻👈

**Comment by onstabb** [comment]
> Пробовал даже сам создать файл, но, увы. Из-за этого не работает «прогулка». 👉🏻👈

Здесь уже моя вина. Но я поправил репозиторий. Замените файл packages.py на новый и удалите тот созданный файл.

**Comment by nikitas244** [comment]
Я уже заново загрузил проект на сервер, но получил вот такое:

**Comment by nikitas244** [comment]
```
root@vm1533475:~/Stay# python3.8 Bot.py
Updates were skipped successfully.
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
^[[1;2ACause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 95, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 82, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running


```

**Comment by nikitas244** [comment]
Тут очень редко получается с Вами связаться, возможно будет другое место связи? Можете написать мне в телеграме t.me/nikitas244.

**Comment by nikitas244** [comment]
Попытки переустановить питон и aiogram не увенчались успехом.

**Comment by nikitas244** [comment]
Не знаю что произошло, но бот поднялся. Но теперь есть беда:

1. На улицу не выходит.
2. Если зайти в "рейтинги" и выйти с него, то ничего происходить не будет, пока не сбросишься до "/start".
3. "Новая" версия бота выглядит вот так: 
![image](https://user-images.githubusercontent.com/8566483/98646323-ce9d0c80-2365-11eb-8d84-2ec4fb19e4ac.png)

Пока это всё. На самой первой версии бота работает и выглядит отлично, но не хочет "гулять".

**Comment by nikitas244** [comment]
Хм, после полного ребута сервера, "улица" запустилась, но бот всё равно отрисовывается вот такой: 
![image](https://user-images.githubusercontent.com/8566483/98663473-bb953700-237b-11eb-9a6a-7febab1afb81.png)

**Comment by onstabb** [comment]
> Тут очень редко получается с Вами связаться, возможно будет другое место связи? Можете написать мне в телеграме t.me/nikitas244.

Я отписал Вам в Telegram

**Comment by nikitas244** [comment]
> > Тут очень редко получается с Вами связаться, возможно будет другое место связи? Можете написать мне в телеграме t.me/nikitas244.
> 
> Я отписал Вам в Telegram

а чего-то не могу найти с вами чат... Киньте, пожалуйста, свой юзернейм.
